# Generated by Django 3.2.3 on 2021-05-17 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_sum', models.IntegerField()),
                ('date_of_finish', models.DateField()),
                ('percent', models.IntegerField()),
                ('debt_admin_status', models.BooleanField()),
                ('debt_status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='wow')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DebtCOntract',
            fields=[
                ('debt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.debt')),
                ('file', models.FileField(upload_to='hz')),
            ],
        ),
        migrations.CreateModel(
            name='WorkInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(blank=True, max_length=50, null=True)),
                ('work_name', models.CharField(blank=True, max_length=50, null=True)),
                ('work_tel', models.CharField(blank=True, max_length=50, null=True)),
                ('work_position', models.CharField(blank=True, max_length=50, null=True)),
                ('work_years', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_index', models.IntegerField(blank=True, null=True)),
                ('register_city', models.CharField(blank=True, max_length=100, null=True)),
                ('register_street', models.CharField(blank=True, max_length=100, null=True)),
                ('register_house', models.IntegerField(blank=True, null=True)),
                ('register_flat', models.IntegerField(blank=True, null=True)),
                ('register_private_house', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassportInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.IntegerField(blank=True, null=True)),
                ('passport_nomder', models.IntegerField(blank=True, null=True)),
                ('passport_date', models.DateField(blank=True, null=True)),
                ('passport_place', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_code', models.CharField(blank=True, max_length=10, null=True)),
                ('passport_photo1', models.ImageField(blank=True, null=True, upload_to='myphoto/')),
                ('passport_photo2', models.ImageField(blank=True, null=True, upload_to='myphoto/')),
                ('passport_photo3', models.ImageField(blank=True, null=True, upload_to='myphoto/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoMainInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_income', models.IntegerField(blank=True, null=True)),
                ('information_family', models.CharField(blank=True, max_length=20, null=True)),
                ('information_education', models.CharField(blank=True, max_length=30, null=True)),
                ('information_car', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MainInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sername', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('your_birthday', models.DateField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('second_tel', models.CharField(blank=True, max_length=50, null=True)),
                ('your_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdressInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.BooleanField(blank=True, null=True)),
                ('adress_index', models.IntegerField(blank=True, null=True)),
                ('adress_city', models.CharField(blank=True, max_length=100, null=True)),
                ('adress_street', models.CharField(blank=True, max_length=100, null=True)),
                ('adress_house', models.IntegerField(blank=True, null=True)),
                ('adress_flat', models.IntegerField(blank=True, null=True)),
                ('adress_private_house', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
